name: Run Gradle Build
on: [ push ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Setup Java
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        name: Setup Gradle

      - name: Execute Gradle build
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        name: Upload built mod JAR
        with:
          name: Farmhelper-Jar
          path: build/libs/*.jar
